version: "3"
services:
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    networks:
      - app-network

  db:
    container_name: db
    restart: unless-stopped
    image: postgres:9.3
    environment:
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
    ports:
      - 15432:5432
    volumes:
      - ./postgresql/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
      - ./postgresql/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
      # - dbdata:/var/lib/postgresql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
